# Generated by Django 2.2.4 on 2019-10-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
