# Generated by Django 2.2.4 on 2019-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='job_title',
            new_name='injuries',
        ),
        migrations.AddField(
            model_name='myuser',
            name='mobile',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
