# Generated by Django 2.2.4 on 2019-11-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191103_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='injuries',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
