# Generated by Django 2.2.4 on 2019-11-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191104_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
    ]
