# Generated by Django 2.2.4 on 2019-11-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191105_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='injuries',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
