# Generated by Django 2.2.4 on 2019-11-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191105_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='done',
            new_name='sold_out',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
